markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Daniel Hengeveld
url: http://thedaniel.github.com
description: Tech stuff from @thedaniel - see also http://neoglam.com
twitter: thedaniel
github: thedaniel
gravatar_url: http://gravatar.com/avatar/04281fcaba85633878f9a451a2e7c4f7